* Book Assessment Test 1
** Assessment blind answers.

[[TODO: Do something]]

1. B, the IP ID is an arbitrary integer that is incremented for each packet. This is how the source and destination keep track of the order of packets to recombine them at the end.
2. C, SQL Injection tries to trick the server into executing SQL code by appending it somewhere. The "OR 1=1" is a common string used for SQL injection because it can be appended to almost anything and return true in SQL.
3. Could be A, B, C, or D.
   - A would be unlikely due to the rigorous verification process of the stores. But sometimes you can find a way.
   - B could certainly be an attack path, if you can get a victim to insert an SD card or USB stick, convince them to run an APK file or something else. 
   - C could also be used, there are third party app stores such as F-droid, you could create an insecure app store as long as you can convince the user to trust and install it.
   - D jailbreaking is a common practice, you could disguise the malware as a jailbreaking tool or state that it requires the user's device to be rooted in order to use it. A rooted device can do so much more than an OEM device. 
4. B, the ARP protocol is used to maintain a table of IP addresses (unsure)
5. C, a buffer overflow is when a program writes into memory beyond the allocated buffer which can impact the values of other variables and thus other functions of the app insecurely.
6. No idea, I understand the fundamental concept here but I do not know how they map to ip ranges.
7. D, I don't actually know, but based on the etymology here I am making a guess. Needs to be studied
8. A, this makes most intuitive sense to me. C doesn't make sense, if probability is higher it should increase risk not decrease.
9. B, This is just an intuitive guess based on word meaning. I'm not sure what a four-way handshake is. Worth studying. 
10. D, Stateful firewalls, iirc will actively inspect packets before they reach the endpoints to find malware signatures. Worth reviewing even if right.
11. D, The other answers can be true sometimes but this is the primary purpose afaik. When configuring new applications we make sure they are aligned with our policies.
12. B, this looks like URL encoding because it uses url codes with percent characters. 
13. B, dig is a DNS tracing tool, we can specify a Name Server record (ns) before or after the domain. Its worth learning the fundamental DNS record types. 
14. A, I believe a DNS Query is sufficient to get this information, may need specific record types. However it is worth learning what a zone transfer is.
15. C, this is just an intuitive guess, this is a topic worth looking into. 
16. D, The only one im uncertain of is if this is considered light on network traffic. You do need to ping a lot of addresses sometimes in a short period of time. But otherwise yeah, pings are very commonly allowed and they don't need a port scan. The downside is that plenty of places like to ignore pings (ICMP)
17. No idea, time to read up. 
18. B, it's common for secure systems to either not have python installed unless absolutely necessary, or they will only allow a specific user to run the python interpreter. A could also be true in some cases. 
19. B, I don't remember the exact syntax, but I believe you can specify source and destination, host would include both. 
20. No clue, need to read on this. 
21. D, although imitation sounds right, I don't remember it being a core principle of social engineering, authority refers to the authority that a help desk demands which induces trust in the victim.
22. No clue, need to read up 
23. No clue, need to read up
24. C, just an intuitive guess, needs review
25. D, i kind of know this, and all the other ones are bullshit lmao
26. C, this is an intuitive guess, privilege escalation would be something you need to exploit the local system for. Which would lead to the others in this list. However, its worth reviewing what they really mean by "local" vulnerability.
27. D, authority is using an "authority" to determine if someone is who they say they are. However this is a bit fuzzy for me. Worth reviewing.
28. D, tailgating is closely following an authorized person to get through a door, man-traps are those rotating contraptions that make sure only one person can enter at a time.
29. A, I have no idea what each of these are other than they are bluetooth attacks. I assume "snarfing" is listening while "jacking" is sending something. So guessing A, but need to review these. 
30. No idea, gotta look up Biba

** Scorin

*** Correctness (did I get the answer right)
#+TBLNAME: scores_table
| #  | Correctness |
|----|-------------|
| 1  | 1           |
| 2  | 1           |
| 3  | 1           |
| 4  | 1           |
| 5  | 1           |
| 6  | 0           |
| 7  | 0           |
| 8  | 1           |
| 9  | 1           |
| 10 | 0           |
| 11 | 0           |
| 12 | 1           |
| 13 | 1           |
| 14 | 0           |
| 15 | 0           |
| 16 | 1           |
| 17 | 0           |
| 18 | 1           |
| 19 | 1           |
| 20 | 0           |
| 21 | 1           |
| 22 | 0           |
| 23 | 0           |
| 24 | 1           |
| 25 | 1           |
| 26 | 1           |
| 27 | 0           |
| 28 | 1           |
| 29 | 0           |
| 30 | 0           |

*** TODO Do something
    DEADLINE:<2025-08-06 Wed>

#+BEGIN_SRC python :var data=scores_table
  print(data)
  return int(100*sum(row[1] for row in data)/sum(1 for i in data))
#+END_SRC

#+RESULTS:
: 56


#+TITLE: CEH Self Assessment Report
#+DESCRIPTION: Assessment of current CEH Knowlege based on book assessment on online official self-assessment

